root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Just plain old shell command. You could use `make` as well.
  cmd = "go build -o ./application.exe ./main.go"
  # Binary file yields from `cmd`.
  bin = "application.exe"
  # Customize binary.
  full_bin = "application.exe"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = true
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  # in milliseconds
  kill_delay = 500 
  log = "air.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = "blue"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
